### PR TITLE
V1/72 deletepaul

### LINKED ISSUE #72: Delete poll
Create laravel controllers for poll deletion
As a presenter
I Want to delete a poll
So it is removed from the presentation
**Estimation: 1h**

### PR DESCRIPTION
**Pull request by kayoumido**

### CODE REVIEW

**Review by SundayBraid — COMMENTED** [review]
## Test

with Postman, an authenticated User with valid Bearer token

- [x] I can delete a poll from a presentation I owned
- [x] I can not delete a poll from a presentation I don't owned
- [x] I can not delete a poll that don't exist (or has been deleted previously) **get a 404 error**

**Review by SundayBraid — APPROVED** [review]
the test are OK

**Review by Lindwing — APPROVED** [review]
- [x] delete a poll

- [x] cannot delete a poll already deleted

- [x] cannot delete a poll not owned

**Comment by kayoumido** [comment]
closes #165

**Pull request merged**
