### PR TITLE
V1/144 unify frontend code

### LINKED ISSUE #144: Unify frontend code
- [x] config authorization bearer token in bootstrap.js
- [x] set default base route in bootstrap.js
- [x] remove double data tag from API
- [x] add a function to retrieve the current user from App.vue and add it as a prop to routerView
- [x] Create a component for alert messages
- [x] Create basic container with title and showMessage logic
- [x] fix all code related to those changes

### PR DESCRIPTION
**Pull request by fabio10000**
# How to test
* Check each component following testing rules based on the original issue

# Bugs
There is a bug with the presentation creation when form is submitted so cannot be fully tested on this PR, but a bug issue as been created to fix that.

### CODE REVIEW

**Review by kayoumido — APPROVED** [review]
Code wise seems all gucci.

# I DID NOT TEST IT

**Review by alfavre — COMMENTED** [review]
I tested:
- [x]  Bearer token correctly loaded from local storage in header (proving that bearer token in bootstrap works)
- [x] Switching route is handled correctly (proving base route works)
- [x] could create a presentation (proving dataform works)
- [x] could create a presentation (proving setLoggedUser works) 
- [x] the alert message is now it's own component (notably, when user logged in and is rerouted, the "Authentifié" alert follows the user on the next "page" (which is great, may have to be tweaked in #134)) 
- [ ]  title and show message have now their own logic, however, they have the same behaviour as the alert message on reroute (following in the next "page"), this is not expected (may have to be tweaked in #134)
- [ ] all code related to those issue isn't fixed, therefore i will not approuve this 

note: the only routes I could not test were the reset and reset password as I got errors (my .env must not be correctly set up)

**Comment by fabio10000** [comment]
> I tested:
> 
>     * [x]   Bearer token correctly loaded from local storage in header (proving that bearer token in bootstrap works)
> 
>     * [x]  Switching route is handled correctly (proving base route works)
> 
>     * [x]  could create a presentation (proving dataform works)
> 
>     * [x]  could create a presentation (proving setLoggedUser works)
> 
>     * [x]  the alert message is now it's own component (notably, when user logged in and is rerouted, the "Authentifié" alert follows the user on the next "page" (which is great, may have to be tweaked in #134))
> 
>     * [x]   title and show message have now their own logic, however, they have the same behaviour as the alert message on reroute (following in the next "page"), this is not expected (may have to be tweaked in #134)
> 
>     * [ ]  all code related to those issue isn't fixed, therefore i will not approuve this
> 
> 
> note: the only routes I could not test were the reset and reset password as I got errors (my .env must not be correctly set up)

* bug fixed concerning the title that didn't update
* The reset password backend cannot be tested as it is not in dev

**Review by alfavre — APPROVED** [review]
Ok

**Pull request merged**
